config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  resource :session, only: %i[ new create destroy ]
  get "posts/search" => "posts#search"
  resources :posts

  resources :posts do
    resources :comments, only: %i[ index create destroy ]
    resources :likes, only: :create
  end

  resources :comments do
    resources :likes, only: :create
  end

  resources :registrations, only: %i[ new create ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likeable, dependent: :destroy

  normalizes :body, with: -> (body) { body.strip }
  
  validates :body, presence: true

  def owned_by(user)
    self.user_id == user&.id
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  # не дает возможности одному пользователю лайкнуть одну и туже запись больше одного раза
  validates :user_id, uniqueness: { scope: %i[ likeable_id likeable_type ] }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, -> { order('created_at DESC') }, dependent: :destroy
  has_rich_text :body

  def created_by(user)
    self.user_id == user.id
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_commit :attach_avatar, on: :create

  has_secure_password
  has_many :likes
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar

  normalizes :email, with: -> (email) { email.strip.downcase }

  validates :email, presence: true, uniqueness: true, format: URI::MailTo::EMAIL_REGEXP
  validates :password, presence: true

  def username
    self.email.split("@").first.capitalize
  end

  def has_like_in? likeable
    likeable.likes.where(user_id: self.id).exists?
  end

  def attach_avatar
    self.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default-user.jpg')), filename: 'default-user.jpg', content_type: 'image/jpeg') unless self.avatar.attached?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :user_logged_in?
  helper_method :current_user
  
  def authenticate_user!
    redirect_to new_session_path, alert: "please log in first" unless user_logged_in?
  end

  def user_logged_in?
    current_user.present?
  end

  def current_user
    User.find_by_id session[:user_id]
  end

  def login user
    reset_session
    session[:user_id] = user.id
  end

  def logout
    reset_session
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :authenticate_user!, except: :index
  before_action :set_post
  before_action :set_comment, only: :destroy

  def index
      render @post.comments.limit(index_params[:limit]).offset(index_params[:offset])
  end

  def create
    @comment = @post.comments.new comment_params
    if @comment.valid?
      @comment.save
      respond_to do |format|
        format.html { redirect_to @post }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to render template: "posts/show", status: :unprocessable_entity }
        format.turbo_stream
      end
    end
  end

  def destroy
    if @comment.owned_by current_user
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to @post }
        format.turbo_stream
      end
    else
      head :unprocessable_entity
    end
  end

  private

  def set_comment
    @comment = Comment.find_by_id params[:id]
  end

  def set_post
    @post = Post.find_by_id params[:post_id]
  end

  def comment_params
    params.require(:comment).permit(:body).merge(user_id: current_user.id)
  end

  def index_params
    params.permit(:offset, :limit).with_defaults(offset: 0, limit: 10)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to posts_path
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :authenticate_user!
  before_action :set_likeable

  def create
    if @likeable.likes.where(user_id: current_user.id).exists?
      @likeable.likes.where(user_id: current_user.id).destroy_all
    else
      @likeable.likes.create(user_id: current_user.id)
    end

    respond_to do |format|
      format.html { redirect_to @likeable }
      format.turbo_stream { render turbo_stream: turbo_stream.replace(dom_id(@likeable, :likes), partial: "likes/button", locals: {likeable: @likeable}) }
    end
  end

  private

    def set_likeable
      @likeable = Post.find_by_id params[:post_id] if params[:post_id]
      @likeable = Comment.find_by_id params[:comment_id] if params[:comment_id]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Pagy::Backend

  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show search ]
  before_action :check_post_owner!, only: %i[ edit update destroy ]

  def index
    @pagy, @posts = pagy(Post.all)
  end

  def show
  end

  def search
    query = "%#{search_params[:query]}%"
    @pagy, @posts = pagy(Post.where("title LIKE ?", query))
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    if @post.valid?
      @post.save
      redirect_to @post, notice: "Post successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @post.update! update_params
      redirect_to @post, notice: "Post updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Post deleted successfully."
  end

  private

    def set_post
      @post = Post.find_by(id: params[:id])
    end

    def search_params
      params.permit(:query).with_defaults(query: "")
    end

    def post_params
      params.require(:post).permit(:title, :body).merge(user_id: current_user.id)
    end

    def update_params
      params.require(:post).permit(:title, :body)
    end

    def check_post_owner!
      redirect_to root_path, alert: "This is not your post scumbag!" unless @post.created_by current_user
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new registration_params
    if @user.valid?
      @user.save
      login @user
      redirect_to root_path, notice: "You have been registered successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def registration_params
    params.require(:user).permit(:email, :password, :avatar, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    cookies[:referrer] = request.referrer
    @user = User.new
  end
  
  def create
    @user = User.authenticate_by login_params

    if @user.present?
      login @user
      url = cookies[:referrer]
      cookies.delete(:referrer)
      redirect_to url, notice: "you have been logged in successfully."
    else
      flash[:alert] = "incorrect email or password."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to new_session_path, notice: "you have been logged out successfully."
  end

  private
  
    def login_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  include Pagy::Frontend

  def search_highlight(content)
    query = params[:query]
    if query
      content.gsub /#{query}/i, '<span class="bg-warning">\0</span>'
    else
      content 
    end
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<% unless comment.new_record? %>
  <%= turbo_frame_tag dom_id(comment, :posts) do %>
    <div class="mb-4">
      <%# body %>
      <div class="d-flex">
        <div class="me-3">
          <%= image_tag comment.user.avatar, class: "rounded-circle", width: 64, height: 64 %>
        </div>
        <div class="">
          <small class="d-block mb-2 text-muted user-select-none" style="font-size: 12px; font-weight: bold;"><%= comment.user.username %></small>
          <%= comment.body %>
          <div class="mt-2"></div>
          <small class="text-muted"><%= time_ago_in_words(comment.created_at) %></small>
          <div class="mt-2 d-flex">
            <%= render 'likes/button', likeable: comment %>
            <% if comment.owned_by current_user %>
              <div class="me-2">
                <%= button_to "delete", post_comment_path(comment.post, comment), method: :delete, class: "btn btn-link" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= turbo_frame_tag "comments_form" do %>
  <%= form_with model: comment, url: post_comments_path(post), method: :post do |form| %>
    <%# Display object errors %>
    <% if form.object.errors.any? %>
      <div class="text-danger">
        <% form.object.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      </div>
    <% end %>
    <%# Display body text-area %>
    <%= form.text_area :body, class: "form-control mb-2" + (form.object.errors.any? ? " border-danger" : ""), rows: 4, placeholder: "Enter text" %>
    <%# Display submit button %>
    <%= form.submit "Send", class: "btn btn-outline-primary" %>
  <% end %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.replace "comments_form" do %>
  <%= render 'comments/form', comment: @comment.errors.any? ? @comment : Comment.new, post: @post %>
<% end %>

<%= turbo_stream.prepend dom_id(@post, "comments_list") do %>
  <%= render partial: "comments/comment", locals: { comment: @comment } %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@comment, :posts) %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloggy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      textarea {
        resize: none;
      }
    </style>
  </head>
  <body class="d-flex flex-column min-vh-100">
    <%# SVG Icons %>
    <%= render "shared/svg_icons" %>
    <%# Header %>
    <%= render "shared/header" %>
    <div class="container">
      <div class="mb-5"></div>
      <%# Success notifications %>
      <% if notice.present? %>
        <div class="alert alert-success mb-4">
          <%= notice %>
        </div>
      <% end %>
      <%# Error notifications %>
      <% if alert.present? %>
        <div class="alert alert-danger mb-4">
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%# footer %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/likes/_button.html.erb
<%= turbo_frame_tag dom_id(likeable, :likes) do %>
  <%= form_with model: [likeable, Like.new], method: :post do |form| %>
    <%= button_tag type: "submit", class: "btn p-0", style: "border: none;" do %>
      <div class="mt-2 d-flex align-items-center">
        <svg class="<% if current_user&.has_like_in? likeable %>text-primary<% end %>" width="16px" height="16px" viewBox="0 -0.5 21 21" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <g id="Page-1" stroke="none" stroke-width="1" fill="currentColor">
            <g id="Dribbble-Light-Preview" transform="translate(-219.000000, -760.000000)" fill="currentColor">
              <g id="icons" transform="translate(56.000000, 160.000000)">
                <path d="M163,610.021159 L163,618.021159 C163,619.126159 163.93975,620.000159 165.1,620.000159 L167.199999,620.000159 L167.199999,608.000159 L165.1,608.000159 C163.93975,608.000159 163,608.916159 163,610.021159 M183.925446,611.355159 L182.100546,617.890159 C181.800246,619.131159 180.639996,620.000159 179.302297,620.000159 L169.299999,620.000159 L169.299999,608.021159 L171.104948,601.826159 C171.318098,600.509159 172.754498,599.625159 174.209798,600.157159 C175.080247,600.476159 175.599997,601.339159 175.599997,602.228159 L175.599997,607.021159 C175.599997,607.573159 176.070397,608.000159 176.649997,608.000159 L181.127196,608.000159 C182.974146,608.000159 184.340196,609.642159 183.925446,611.355159" id="like-[#1386]"></path>
              </g>
            </g>
          </g>
        </svg>
        <div class="ms-2" style="color: #777777;">
          <%= likeable.likes.size %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: @post, url: @post.new_record? ? posts_path : post_path(@post), method: @post.new_record? ? :post : :patch do |form| %>
  <%# Display object errors %>
  <% if form.object.errors.any? %>
    <div class="text-danger">
      <% form.object.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>
  <%# Title %>
  <div class="form-group mb-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <%# body %>
  <div class="form-group mb-3">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>
  <%# Title %>
  <div class="form-group">
    <%= form.submit @post.new_record? ? "Create post" : "Update post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%# verbose %>
<div class="mb-5">
  <%# Head %>
  <% if verbose %>
    <h2>
      <%= post.title %>
    </h2>
  <% else %>
    <%= link_to raw(search_highlight(post.title)), post_path(post), class: "text-capitalize fs-2 d-block" %>
  <% end %>
  <div class="d-flex">
    <%= link_to "edit", edit_post_path(post), class: "me-2" if post.created_by current_user %>
    <%= button_to "delete", post_path(post), class: "p-0 btn btn-link",method: :delete if post.created_by current_user %>
  </div>
  <small class="text-muted d-block">Created: <%= time_ago_in_words(post.created_at) %></small>
  <small class="text-muted d-block">Author: <%= post.user.username %></small>
  <%# Body %>
  <div class="mt-2">
    <% if verbose %>
      <%= post.body %>
    <% else %>
      <%= truncate(post.body.to_plain_text, length: 25, omission: " ... %s") % link_to('read more', post_path(post)) %>
    <% end %>
  </div>
  <%# Footer %>
  <% if verbose %>
    <%= render 'likes/button', likeable: post %>
  <% else %>
    <div class="d-flex align-items-center mt-2">
      <%= render "shared/comments_count", post: post %>
      <div class="me-3"></div>
      <%= render "shared/likes_count", post: post %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="mb-4">
  <%== pagy_bootstrap_nav @pagy, class: "mx-auto" %>
</div>
<%= render @posts, verbose: false %>
<div class="mt-4">
  <%== pagy_bootstrap_nav @pagy, class: "mx-auto" %>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post, url: posts_path, method: :post do |form| %>
  <%# Display object errors %>
  <% if form.object.errors.any? %>
    <div class="text-danger">
      <% form.object.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>
  <%# Title %>
  <div class="form-group mb-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <%# body %>
  <div class="form-group mb-3">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>
  <%# Title %>
  <div class="form-group">
    <%= form.submit "Create post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/search.html.erb
<% if @posts.length == 0 %>
  <p class="text-center">No results</p>
<% else %>
  <p class="text-center"><%= pluralize(@pagy.count, "result") %></p>
<% end %>
<div class="my-4">
  <%== pagy_bootstrap_nav @pagy, class: "mx-auto" %>
</div>
<%= render @posts, verbose: false %>
<div class="mt-4">
  <%== pagy_bootstrap_nav @pagy, class: "mx-auto" %>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-12">
    <%= render @post, verbose: true %>
    <%# Comments section %>
    <div class="mt-5 text-center fs-5">
      Comments:
    </div>
    <div class="mt-3">
      <%# Form for the new comment %>
      <%= render 'comments/form', comment: @comment || Comment.new, post: @post %>
      <%# Display comments list %>
      <div class="mt-4"></div>
      <%= turbo_frame_tag dom_id(@post, "comments_list") do %>
        <%= render @post.comments.limit(10).offset(0) %>
      <% end %>
      <div data-controller="more-comments" data-more-comments-comments-list-id-value=<%= dom_id(@post, "comments_list") %> data-more-comments-post-id-value=<%= @post.id %>>
        <%= button_tag "More comments", class: "d-block mx-auto btn btn-link-primary", data: { action: "click->more-comments#click" } %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_comments_count.html.erb
<div class="d-flex align-items-center">
  <svg  version="1.0" 
        id="Layer_1" 
        xmlns="http://www.w3.org/2000/svg" 
        xmlns:xlink="http://www.w3.org/1999/xlink" 
        width="14px" 
        height="14px" 
        viewBox="0 0 64 64" 
        enable-background="new 0 0 64 64" 
        xml:space="preserve" 
        class="mt-1">
    <path fill-rule="evenodd" 
          clip-rule="evenodd" 
          fill="#777777" 
          d="M60,0H4C1.789,0,0,1.789,0,4v40c0,2.211,1.789,4,4,4h8v12
              c0,1.617,0.973,3.078,2.469,3.695C14.965,63.902,15.484,64,16,64c1.039,0,2.062-0.406,2.828-1.172L33.656,48H60c2.211,0,4-1.789,4-4
              V4C64,1.789,62.211,0,60,0z"/>
  </svg>
  <div class="ms-2" style="color: #777777;">
    <%= post.comments.size %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="container mt-auto">
  <div class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-muted">© <%= Date.today.year %> SCM Group, Inc</span>
    </div>
    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="https://x.com/"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="https://instagram.com/"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="https://facebook.com/"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>
  </div>
</div>

app/views/shared/_header.html.erb
<header class="p-3 mb-3 sticky-top bg-white" style="box-shadow: 0 4px 2px -2px rgba(0, 0, 0, .1);">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/" class="nav-link px-2 link-dark">Home</a></li>
        <li><%= link_to "Posts", posts_path, class: "nav-link px-2 link-dark" %></li>
      </ul>
      <!--form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
      </form-->
      <%= form_tag posts_search_path, class: "col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3", method: :get do %>
        <%= text_field_tag "query", nil, class: "form-control", placeholder: "Search...", aria_label: "Search" %>
      <% end %>
      <% if user_logged_in? %>  
        <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <%= image_tag current_user.avatar, class: "rounded-circle", width: 32, height: 32 %>
          </a>
          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
            <li><%= link_to "New Post", new_post_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= button_to "Sign out", session_path, class: "dropdown-item", method: :delete %></li>
          </ul>
        </div>
      <% else %>
        <div class="text-end">
          <%= link_to "Login", new_session_path, class: "btn btn-outline-primary me-2" %>
          <%= link_to "Sign-up", new_registration_path, type: "button", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_likes_count.html.erb
<div class="d-flex align-items-center">
  <svg width="16px" height="16px" viewBox="0 -0.5 21 21" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
      <g id="Dribbble-Light-Preview" transform="translate(-219.000000, -760.000000)" fill="#777777">
        <g id="icons" transform="translate(56.000000, 160.000000)">
          <path d="M163,610.021159 L163,618.021159 C163,619.126159 163.93975,620.000159 165.1,620.000159 L167.199999,620.000159 L167.199999,608.000159 L165.1,608.000159 C163.93975,608.000159 163,608.916159 163,610.021159 M183.925446,611.355159 L182.100546,617.890159 C181.800246,619.131159 180.639996,620.000159 179.302297,620.000159 L169.299999,620.000159 L169.299999,608.021159 L171.104948,601.826159 C171.318098,600.509159 172.754498,599.625159 174.209798,600.157159 C175.080247,600.476159 175.599997,601.339159 175.599997,602.228159 L175.599997,607.021159 C175.599997,607.573159 176.070397,608.000159 176.649997,608.000159 L181.127196,608.000159 C182.974146,608.000159 184.340196,609.642159 183.925446,611.355159" id="like-[#1386]"></path>
        </g>
      </g>
    </g>
  </svg>
  <div class="ms-2" style="color: #777777;">
    <%= post.likes.size %>
  </div>
</div>